spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: austin
    password: austinmysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  .profiles:
    active=prod:

jwt:
  secret: your-256-bit-secret-key-1234567890abcdef
  access-token-expiry: 900000   # 15ë¶„
  refresh-token-expiry: 604800000
server:
  port: 9090
