
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: austin
    password: austinmysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  .profiles:
    active=prod:

  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: "6NaYylkfpXOyXEas0EE7"
            client-secret: "QRLs896biA"
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: Naver
#
#          google:
#            client-id: GOOGLE_CLIENT_ID
#            client-secret: GOOGLE_CLIENT_SECRET
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            scope: profile,email
#            client-name: Google

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



jwt:
  secret: your-256-bit-secret-key-1234567890abcdef
  access-token-expiry: 450000   # 7ë¶„
  refresh-token-expiry: 604800000
server:
  port: 9090
