spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: austin
    password: austinmysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  .profiles:
    active=prod:
#logging:
#  level:
#    org.hibernate.SQL: OFF
#    org.hibernate.orm.jdbc.bind: OFF
#    org.hibernate.engine.jdbc.spi.SqlStatementLogger: OFF
#    org.hibernate.type.descriptor.sql.BasicBinder: OFF
jwt:
  secret: your-256-bit-secret-key-1234567890abcdef
  access-token-expiry: 450000   # 15ë¶„
  refresh-token-expiry: 604800000
server:
  port: 9090
